name: uas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter
  http: ^1.1.0
  image_picker: ^1.0.7
  sqflite: ^2.0.0+2
  sqflite_common_ffi: ^2.0.0+3
  sqflite_common_ffi_web: ^0.4.2+3
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets: 
    - assets/
